model:
  base_learning_rate: 5.0e-6   # set to target_lr by starting main.py with '--scale_lr False'
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    ckpt_path: "/home/hice1/skamath36/scratch/latent-diffusion-ML-Limited-Supervision/logs/2023-11-23T15-40-13_voicebank-ldm-kl-9/checkpoints/epoch=000004.ckpt"
    linear_start: 0.0015
    linear_end: 0.0155
    num_timesteps_cond: 1
    log_every_t: 20
    timesteps: 100
    loss_type: l1
    first_stage_key: "image"
    image_size: 171
    channels: 32
    cond_stage_trainable: False
    concat_mode: False
    scale_by_std: True
    monitor: 'val/loss_simple_ema'

    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [10000]
        cycle_lengths: [10000000000000]
        f_start: [1.e-6]
        f_max: [1.]
        f_min: [ 1.]

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 171
        in_channels: 32
        out_channels: 32
        model_channels: 64
        attention_resolutions: [ ]   # 32, 16, 8, 4
        num_res_blocks: 1
        channel_mult: [ 1,2 ]  # 32, 16, 8, 4, 2
        num_heads: 1
        use_scale_shift_norm: True
        resblock_updown: True

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        monitor: "val/rec_loss"
        embed_dim: 32
        ckpt_path: "/home/hice1/skamath36/scratch/latent-diffusion-ML-Limited-Supervision/logs/2023-11-21T12-42-22_autoencoder_kl_57x9x32_spec/checkpoints/epoch=000024.ckpt"
        lossconfig:
          target: torch.nn.Identity

        ddconfig:
          double_z: True
          z_channels: 32
          resolution: 256
          in_channels: 1
          out_ch: 1
          ch: 32
          ch_mult: [1,2,4]  # num_down = len(ch_mult)-1
          num_res_blocks: 1
          resamp_with_conv: False
          attn_resolutions: []
          dropout: 0.0

    cond_stage_config: "__is_unconditional__"

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 12
    wrap: True
    num_workers: 5
    train:
      target: ldm.data.voicebank.VoiceBankTrain
      params:
        npy_path: "/home/hice1/skamath36/scratch/latent-diffusion-ML-Limited-Supervision/spec/voicebank_Clean/train"
        crop: 243
    validation:
      target: ldm.data.voicebank.VoiceBankValidation
      params:
        npy_path: "/home/hice1/skamath36/scratch/latent-diffusion-ML-Limited-Supervision/spec/voicebank_Clean/valid"
        crop: 243

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 5000
        max_images: 8
        increase_log_steps: False


  trainer:
    benchmark: True